/** NUI event constants organized by domain */
export const NUI_EVENTS = {
	DASHBOARD: {
		GET_JOB_DATA: "getJobData",
		GET_REPORT_STATISTICS: "getReportStatistics",
		GET_TIME_STATISTICS: "getTimeStatistics",
		GET_ACTIVE_WARRANTS: "getActiveWarrants",
		GET_BULLETINS: "getBulletins",
		CREATE_BULLETIN: "createBulletin",
		DELETE_BULLETIN: "deleteBulletin",
		GET_RECENT_REPORTS: "getRecentReports",
		GET_ACTIVE_BOLOS: "getActiveBolos",
		GET_ACTIVE_UNITS: "getActiveUnits",
		GET_RECENT_DISPATCHES: "getRecentDispatches",
		GET_USAGE_METRICS: "getUsageMetrics",
		UPDATE_JOB_DATA: "updateJobData",
		UPDATE_REPORT_STATISTICS: "updateReportStatistics",
		UPDATE_TIME_STATISTICS: "updateTimeStatistics",
		UPDATE_ACTIVE_WARRANTS: "updateActiveWarrants",
		UPDATE_BULLETINS: "updateBulletins",
		UPDATE_RECENT_REPORTS: "updateRecentReports",
		UPDATE_ACTIVE_BOLOS: "updateActiveBolos",
		UPDATE_ACTIVE_UNITS: "updateActiveUnits",
		UPDATE_RECENT_DISPATCHES: "updateRecentDispatches",
		UPDATE_USAGE_METRICS: "updateUsageMetrics",
	},
	DISPATCH: {
		ATTACH_TO_DISPATCH: "attachToDispatch",
		DETACH_FROM_DISPATCH: "detachFromDispatch",
		ROUTE_TO_DISPATCH: "routeToDispatch",
	},
	NAVIGATION: {
		VIEW_WARRANT: "viewWarrant",
		VIEW_REPORT: "viewReport",
		TOGGLE_DUTY: "toggleDuty",
		CLOSE_UI: "closeUI",
		SET_TOP_BAR_HOVER: "setTopBarHover",
		SET_VISIBLE: "setVisible",
	},
	AUTH: {
		LOGIN: "login",
		LOGOUT: "logout",
		CHECK_AUTH: "checkAuth",
		UPDATE_AUTH: "updateAuth",
		SIGN_OUT: "signOut",
		GO_ON_DUTY: "toggleDuty",
		GET_MY_PERMISSIONS: "getMyPermissions",
	},
	REPORT: {
		CREATE_REPORT: "createReport",
		UPDATE_REPORT: "updateReport",
		DELETE_REPORT: "deleteReport",
		GET_REPORT: "getReport",
		GET_REPORTS: "getReports",
		GET_REPORT_ANALYTICS: "getReportAnalytics",
		SEARCH_REPORTS: "searchReports",
		GET_AVAILABLE_TAGS: "getAvailableTags",
		SEARCH_OFFICERS: "searchOfficers",
		SEARCH_PLAYERS: "searchPlayers",
		SAVE_REPORT: "saveReport",
		UPDATE_REPORTS: "updateReports",
		UPLOAD_EVIDENCE_IMAGE: "uploadEvidenceImage",
		GENERATE_REPORT_ID: "generateReportId",
		SEARCH_VEHICLES_FOR_REPORT: "searchVehiclesForReport",
	},
	CITIZEN: {
		GET_CITIZENS: "getCitizens",
		SEARCH_CITIZENS: "searchCitizens",
		GET_CITIZEN: "getCitizen",
		UPDATE_CITIZEN: "updateCitizen",
		GET_BOLOS: "getBolos",
		CREATE_BOLO: "createBolo",
		UPDATE_BOLO_STATUS: "updateBoloStatus",
		DELETE_BOLO: "deleteBolo",
		VIEW_CITIZEN_PROFILE: "viewCitizenProfile",
		VIEW_BOLO: "viewBolo",
		UPDATE_CITIZENS: "updateCitizens",
		UPDATE_BOLOS: "updateBolos",
		UPDATE_CITIZEN_LICENSE: "updateCitizenLicense",
		UPDATE_CITIZEN_CUSTOM_LICENSE: "updateCitizenCustomLicense",
		TRIGGER_SUSPECT_MUGSHOT: "triggerSuspectMugshot",
		UPLOAD_SUSPECT_PHOTO: "uploadSuspectPhoto",
		ADD_SUSPECT_FINGERPRINT: "addSuspectFingerprint",
		UPDATE_CITIZEN_DNA: "updateCitizenDNA",
		UPDATE_CITIZEN_FINGERPRINT: "updateCitizenFingerprint",
	},
	VEHICLE: {
		GET_VEHICLES: "getVehicles",
		SEARCH_VEHICLES: "searchVehicles",
		GET_VEHICLE: "getVehicle",
		UPDATE_VEHICLE: "updateVehicle",
		GET_REPORTS_BY_PLATE: "getReportsByPlate",
	},
	WEAPON: {
		GET_WEAPONS: "getWeapons",
		SEARCH_WEAPONS: "searchWeapons",
		GET_WEAPON: "getWeapon",
		GET_WEAPON_HISTORY: "getWeaponOwnershipHistory",
		UPDATE_WEAPON: "updateWeapon",
	},
	CHARGE: {
		GET_CHARGES: "getCharges",
		ADD_CHARGE: "addCharge",
		UPDATE_CHARGE: "updateCharge",
		DELETE_CHARGE: "deleteCharge",
	},
	WARRANT: {
		ISSUE_WARRANT: "issueWarrant",
		CLOSE_WARRANT: "closeWarrant",
	},
	SENTENCING: {
		SEND_TO_JAIL: "sendToJail",
		GIVE_CITATION: "giveCitation",
	},
	ROSTER: {
		GET_ROSTER: "getRoster",
		UPDATE_ROSTER: "updateRoster",
		ADD_OFFICER: "addOfficer",
		REMOVE_OFFICER: "removeOfficer",
		GET_ACTIVE_UNITS: "getActiveUnits",
		GET_OFFICER_TAGS: "getOfficerTags",
		UPDATE_OFFICER_CERTIFICATIONS: "updateOfficerCertifications",
		GET_JOB_GRADES: "getJobGrades",
		PROMOTE_OFFICER: "promoteOfficer",
		FIRE_OFFICER: "fireOfficer",
		UPDATE_CALLSIGN: "updateOfficerCallsign",
	},
	PPR: {
		GET_PPR_LIST: "getPPRList",
		GET_PPR: "getPPR",
		GET_OFFICER_PPR_HISTORY: "getOfficerPPRHistory",
		CREATE_PPR: "createPPR",
		UPDATE_PPR: "updatePPR",
		DELETE_PPR: "deletePPR",
		ADD_PPR_NOTE: "addPPRNote",
		DELETE_PPR_NOTE: "deletePPRNote",
	},
	FTO: {
		GET_FTO_LIST: "getFTOList",
		GET_FTO: "getFTO",
		GET_OFFICER_FTO_HISTORY: "getOfficerFTOHistory",
		CREATE_FTO_ASSIGNMENT: "createFTOAssignment",
		UPDATE_FTO_ASSIGNMENT: "updateFTOAssignment",
		DELETE_FTO_ASSIGNMENT: "deleteFTOAssignment",
		CREATE_FTO_DOR: "createFTODor",
		DELETE_FTO_DOR: "deleteFTODor",
		GET_FTO_PHASES: "getFTOPhases",
		SAVE_FTO_PHASES: "saveFTOPhases",
		GET_FTO_COMPETENCIES: "getFTOCompetencies",
		SAVE_FTO_COMPETENCIES: "saveFTOCompetencies",
	},
	CASE: {
		CREATE_CASE: "createCase",
		GET_CASES: "getCases",
		GET_CASE: "getCase",
		GET_CASE_EVIDENCE_PAGE: "getCaseEvidencePage",
		UPDATE_CASE: "updateCase",
		DELETE_CASE: "deleteCase",
		LINK_REPORT_TO_CASE: "linkReportToCase",
		UNLINK_REPORT_FROM_CASE: "unlinkReportFromCase",
		ASSIGN_CASE_OFFICER: "assignCaseOfficer",
		REMOVE_CASE_OFFICER: "removeCaseOfficer",
		ADD_CASE_ATTACHMENT: "addCaseAttachment",
		REMOVE_CASE_ATTACHMENT: "removeCaseAttachment",
		ADD_CASE_ATTACHMENT_UPLOAD: "addCaseAttachmentUpload",
		ADD_EVIDENCE_ITEM: "addEvidenceItem",
		UPDATE_EVIDENCE_ITEM: "updateEvidenceItem",
		TRANSFER_EVIDENCE_ITEM: "transferEvidenceItem",
		DELETE_EVIDENCE_ITEM: "deleteEvidenceItem",
		GET_EVIDENCE_CUSTODY: "getEvidenceCustody",
		ADD_EVIDENCE_IMAGE: "addEvidenceImage",
		REMOVE_EVIDENCE_IMAGE: "removeEvidenceImage",
		LINK_EVIDENCE_TO_CASE: "linkEvidenceToCase",
		CREATE_CASE_FROM_EVIDENCE: "createCaseFromEvidence",
		ADD_CASE_NOTE: "addCaseNote",
		DELETE_CASE_NOTE: "deleteCaseNote",
	},
	EVIDENCE: {
		GET_EVIDENCE_ITEMS: "getEvidenceItems",
		SEARCH_EVIDENCE_ITEMS: "searchEvidenceItems",
		ADD_EVIDENCE_ITEM: "addEvidenceItem",
		UPDATE_EVIDENCE_ITEM: "updateEvidenceItem",
		DELETE_EVIDENCE_ITEM: "deleteEvidenceItem",
		TRANSFER_EVIDENCE_ITEM: "transferEvidenceItem",
		GET_EVIDENCE_CUSTODY: "getEvidenceCustody",
		ADD_EVIDENCE_IMAGE: "addEvidenceImage",
		REMOVE_EVIDENCE_IMAGE: "removeEvidenceImage",
		LINK_EVIDENCE_TO_CASE: "linkEvidenceToCase",
		LINK_EVIDENCE_TO_REPORT: "linkEvidenceToReport",
		CREATE_CASE_FROM_EVIDENCE: "createCaseFromEvidence",
		OPEN_EVIDENCE_STASH: "openEvidenceStash",
		LOG_EVIDENCE_VIEWED: "logEvidenceViewed",
	},
	AUDIT: {
		GET_AUDIT_LOGS: "getAuditLogs",
		GET_AUDIT_LOGS_BY_CASE: "getAuditLogsByCase",
	},
	CAMERA: {
		GET_CAMERAS: "getCameras",
		VIEW_CAMERA: "viewCamera",
	},
	BODYCAM: {
		GET_BODYCAMS: "getBodycams",
		VIEW_BODYCAM: "viewBodycam",
	},
	MAP: {
		GET_TRACKING: "getTracking",
	},
	MANAGEMENT: {
		GET_PERMISSION_ROLES: "getPermissionRoles",
		UPDATE_PERMISSION_ROLE: "updatePermissionRole",
		GET_TAGS: "getTags",
		CREATE_TAG: "createTag",
		UPDATE_TAG: "updateTag",
		DELETE_TAG: "deleteTag",
	},
	AWARDS: {
		GET_AWARDS_DATA: "getAwardsData",
		GET_AWARD_CONFIGS: "getAwardConfigs",
		SAVE_AWARD: "saveAward",
		DELETE_AWARD: "deleteAward",
	},
	SETTINGS: {
		GET_AUDIT_TRACKING: "getAuditTrackingConfig",
		SAVE_AUDIT_TRACKING: "saveAuditTrackingConfig",
		GET_JAIL_FINES_CONFIG: "getJailFinesConfig",
		SAVE_JAIL_FINES_CONFIG: "saveJailFinesConfig",
		GET_REPORT_TEMPLATES: "getReportTemplates",
		SAVE_REPORT_TEMPLATE: "saveReportTemplate",
		DELETE_REPORT_TEMPLATE: "deleteReportTemplate",
		GET_CUSTOM_LICENSES: "getCustomLicenses",
		SAVE_CUSTOM_LICENSE: "saveCustomLicense",
		DELETE_CUSTOM_LICENSE: "deleteCustomLicense",
		GET_COLOR_CONFIG: "getColorConfig",
		SAVE_COLOR_CONFIG: "saveColorConfig",
	},
	IA: {
		GET_IA_COMPLAINTS: "getIAComplaints",
		GET_IA_COMPLAINT: "getIAComplaint",
		GET_IA_HISTORY_FOR_OFFICER: "getIAHistoryForOfficer",
		UPDATE_IA_COMPLAINT_INFO: "updateIAComplaintInfo",
		UPDATE_IA_STATUS: "updateIAStatus",
		ASSIGN_IA_COMPLAINT: "assignIAComplaint",
		ADD_IA_NOTE: "addIANote",
		DELETE_IA_NOTE: "deleteIANote",
	},
	CIVILIAN: {
		GET_MY_PROFILE: "getMyProfile",
	},
	COLLAB: {
		JOIN_REPORT_SESSION: "joinReportSession",
		LEAVE_REPORT_SESSION: "leaveReportSession",
		SYNC_REPORT_DATA: "syncReportData",
	},
	DOJ: {
		GET_COURT_CASES: "getCourtCases",
		GET_COURT_CASE: "getCourtCase",
		CREATE_COURT_CASE: "createCourtCase",
		UPDATE_COURT_CASE: "updateCourtCase",
		GET_WARRANT_REQUESTS: "getWarrantRequests",
		REVIEW_WARRANT_REQUEST: "reviewWarrantRequest",
		CREATE_WARRANT_REQUEST: "createWarrantRequest",
		GET_COURT_ORDERS: "getCourtOrders",
		CREATE_COURT_ORDER: "createCourtOrder",
		UPDATE_COURT_ORDER: "updateCourtOrder",
		REVOKE_COURT_ORDER: "revokeCourtOrder",
		GET_LEGAL_DOCUMENTS: "getLegalDocuments",
		GET_LEGAL_DOCUMENT: "getLegalDocument",
		CREATE_LEGAL_DOCUMENT: "createLegalDocument",
		UPDATE_LEGAL_DOCUMENT: "updateLegalDocument",
		DELETE_LEGAL_DOCUMENT: "deleteLegalDocument",
		GET_DOJ_DASHBOARD: "getDojDashboard",
	},
	SOP: {
		GET_SOP_CATEGORIES: "getSOPCategories",
		CREATE_SOP_CATEGORY: "createSOPCategory",
		UPDATE_SOP_CATEGORY: "updateSOPCategory",
		DELETE_SOP_CATEGORY: "deleteSOPCategory",
		CREATE_SOP_SECTION: "createSOPSection",
		UPDATE_SOP_SECTION: "updateSOPSection",
		DELETE_SOP_SECTION: "deleteSOPSection",
		GET_SOP_SETTINGS: "getSOPSettings",
		UPDATE_SOP_MISSION: "updateSOPMission",
		UPDATE_SOP_INTRO: "updateSOPIntro",
		PUBLISH_SOP: "publishSOP",
		CHECK_SOP_AGREEMENT: "checkSOPAgreement",
		ACKNOWLEDGE_SOP: "acknowledgesSOP",
	},
} as const;

// Backwards compatibility exports (deprecated - use NUI_EVENTS instead)
export const DASHBOARD_EVENTS = NUI_EVENTS.DASHBOARD;
export const DISPATCH_EVENTS = NUI_EVENTS.DISPATCH;
export const NAVIGATION_EVENTS = NUI_EVENTS.NAVIGATION;
export const AUTH_EVENTS = NUI_EVENTS.AUTH;
export const REPORT_EVENTS = NUI_EVENTS.REPORT;
export const CITIZEN_EVENTS = NUI_EVENTS.CITIZEN;
export const VEHICLE_EVENTS = NUI_EVENTS.VEHICLE;
export const WEAPON_EVENTS = NUI_EVENTS.WEAPON;
export const CHARGE_EVENTS = NUI_EVENTS.CHARGE;
export const ROSTER_EVENTS = NUI_EVENTS.ROSTER;
export const DOJ_EVENTS = NUI_EVENTS.DOJ;

// All events combined for type checking
export const ALL_NUI_EVENTS = [
	...Object.values(NUI_EVENTS.DASHBOARD),
	...Object.values(NUI_EVENTS.DISPATCH),
	...Object.values(NUI_EVENTS.NAVIGATION),
	...Object.values(NUI_EVENTS.AUTH),
	...Object.values(NUI_EVENTS.REPORT),
	...Object.values(NUI_EVENTS.CITIZEN),
	...Object.values(NUI_EVENTS.VEHICLE),
	...Object.values(NUI_EVENTS.WEAPON),
	...Object.values(NUI_EVENTS.CHARGE),
	...Object.values(NUI_EVENTS.WARRANT),
	...Object.values(NUI_EVENTS.SENTENCING),
	...Object.values(NUI_EVENTS.ROSTER),
	...Object.values(NUI_EVENTS.CAMERA),
	...Object.values(NUI_EVENTS.BODYCAM),
	...Object.values(NUI_EVENTS.CASE),
	...Object.values(NUI_EVENTS.EVIDENCE),
	...Object.values(NUI_EVENTS.AUDIT),
	...Object.values(NUI_EVENTS.MAP),
	...Object.values(NUI_EVENTS.MANAGEMENT),
	...Object.values(NUI_EVENTS.AWARDS),
	...Object.values(NUI_EVENTS.SETTINGS),
	...Object.values(NUI_EVENTS.IA),
	...Object.values(NUI_EVENTS.PPR),
	...Object.values(NUI_EVENTS.FTO),
	...Object.values(NUI_EVENTS.CIVILIAN),
	...Object.values(NUI_EVENTS.COLLAB),
	...Object.values(NUI_EVENTS.DOJ),
	...Object.values(NUI_EVENTS.SOP),
	"copyToClipboard",
	"submitComplaint",
	"closeComplaint",
	"reportEditorJoined",
	"reportEditorLeft",
	"reportDataUpdate",
	"syncYjsUpdate",
	"yjsUpdate",
	"yjsBatch",
	"pollYjsUpdates",
] as const;

export type WeaponNuiEvents = typeof NUI_EVENTS.WEAPON;

// Type for all valid NUI event names
export type NuiEventName = (typeof ALL_NUI_EVENTS)[number];
