Config = Config or {}

Config.RosterLink = {
    ['police'] = '',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['doj'] = '',
}


Config.UseWolfknightRadar = true
Config.WolfknightNotifyTime = 5000 --How long the notification displays for in miliseconds (30000 = 30 seconds)
--[[
Adds support for Wraith ARS 2X by WolfKnight98 (wk_wars2x)
https://github.com/WolfKnight98/wk_wars2x
To save on unnecessary database queries, in wk_wars2x/config.lua set 'CONFIG.use_sonorancad = true'
This will only check plates of vehicles that have been occupied by a player
--]]

Config.OnlyShowOnDuty = true

Config.Fuel = "lj-fuel" -- "LegacyFuel", "lj-fuel"

Config.PenalCodeTitles = {
    [1] = 'ASSAULT/MURDER',
    [2] = 'THEFT / BURGLARY',
    [3] = 'DRUGS',
    [4] = 'PROPERTY DAMAGE / ENVIRONMENT',
    [5] = 'WEAPONS',
    [6] = 'PUBLIC ORDER AND CUSTODY',
    [7] = 'OBSTRUCT JUSTICE / CORRUPTION',
    [8] = 'FIREARMS',
    [9] = 'TRAFFIC - GENERAL',
    [10] = 'TRAFFIC - LICENSING / DEFECTS',
    [11] = 'TRAFFIC - LIGHTS / MARKINGS',
    [12] = 'TRAFFIC - VEHICLE OPERATION',
    [13] = 'TRAFFIC - SPEEDING',
    [14] = 'TRAFFIC - DRINK / DRUG DRIVING',
}

Config.PenalCode = {
    -- Assault / Murder
    [1] = {
        [1] = {title = 'Murder', class = 'Strictly Indictable', id = 'Sect 18 Crimes Act', months = 100, fine = 200000, color = 'red'},
        [1] = {title = 'Murder emergency services worker', class = 'Strictly Indictable', id = 'Sect 18 Crimes Act', months = 150, fine = 250000, color = 'red'},
        [2] = {title = 'Attempted Murder', class = 'Strictly Indictable', id = 'Sect 27 Crimes Act', months = 90, fine = 150000, color = 'red'},
        [3] = {title = 'Att. Murder emergency services worker', class = 'Strictly Indictable', id = 'Sect 27 Crimes Act', months = 120, fine = 200000, color = 'red'},
        [4] = {title = 'Manslaughter', class = 'Strictly Indictable', id = 'Sect 18 Crimes Act', months = 70, fine = 30000, color = 'Red'},
        [5] = {title = 'Conspiring to Commit Murder', class = 'Strictly Indictable', id = 'Sect 26 Crimes Act', months = 70, fine = 100000, color = 'red'},
        [6] = {title = 'Assault Causing Death', class = 'Strictly Indictable', id = 'Sect 25A Crimes Act', months = 60, fine = 80000, color = 'red'},
        [7] = {title = 'Intentional Wounding or grevious bodily harm', class = 'Indictable', id = 'Sect 33 Crimes Act', months = 60, fine = 70000, color = 'red'},
        [8] = {title = 'Reckless grevious bodily harm or wounding', class = 'Indictable', id = 'Sect 35 Crimes Act', months = 50, fine = 50000, color = 'red'},
        [9] = {title = 'Spiking Drink or Food', class = 'Indictable', id = 'Sect 38A Crimes Act', months = 20, fine = 10000, color = 'orange'},
        [10] = {title = 'Assault occassioning actual bodily harm', class = 'Indictable', id = 'Sect 59 Crimes Act', months = 30, fine = 10000, color = 'orange'},
        [11] = {title = 'Assault during public disorder', class = 'Indictable', id = 'Sect 59A Crimes Act', months = 30, fine = 10000, color = 'orange'},
        [12] = {title = 'Assault occassioning actual bodily harm', class = 'Indictable', id = 'Sect 59 Crimes Act', months = 30, fine = 10000, color = 'orange'},
        [13] = {title = 'Assault police in execution of duty', class = 'Indictable', id = 'Sect 60(1) Crimes Act', months = 30, fine = 10000, color = 'orange'},
        [14] = {title = 'Throw missile at Police in exec. of duty', class = 'Indictable', id = 'Sect 60(1) Crimes Act', months = 30, fine = 10000, color = 'orange'},
        [15] = {title = 'Stalk/Harrass/Intimidate Police in exec. of duty', class = 'Indictable', id = 'Sect 60(1) Crimes Act', months = 30, fine = 10000, color = 'orange'},
        [16] = {title = 'Assault police causing bodily harm', class = 'Indictable', id = 'Sect 60(2) Crimes Act', months = 40, fine = 15000, color = 'orange'},
        [17] = {title = 'Kidnapping', class = 'Strictly Indictable', id = 'Sect 86 Crimes Act', months = 60, fine = 50000, color = 'red'},
        [18] = {title = 'Blackmail', class = 'Indictable', id = 'Sect 249K Crimes Act', months = 10, fine = 10000, color = 'orange'},
        [19] = {title = 'Common Assault', class = 'Indictable', id = 'Sect 61 Crimes Act', months = 10, fine = 10000, color = 'orange'},
        [20] = {title = 'Stalking', class = 'Indictable', id = 'S8 Crimes (DPV) Act', months = 20, fine = 10000, color = 'orange'},
        [21] = {title = 'Intimidation', class = 'Indictable', id = 'Sect 7 Crime (DPV) Act', months = 20, fine = 10000, color = 'orange'},

    },
     -- Theft / Burglary
    [2] = {

        [1] = {title = 'Robbery', class = 'Indictable', id = 'Sect 94 Crimes Act', months = 40, fine = 40000, color = 'orange'},
        [2] = {title = 'Attempted Robbery', class = 'Indictable', id = 'Sect 94 Crimes Act', months = 30, fine = 30000, color = 'orange'},
        [3] = {title = 'Aggravated Robbery', class = 'Indictable', id = 'Sect 95 Crimes Act', months = 50, fine = 50000, color = 'red'},
        [4] = {title = 'Burglary (Break and Enter)', class = 'Indictable', id = 'Sect 109 Crimes Act', months = 20, fine = 10000, color = 'orange'},
        [5] = {title = 'Armed w/ intent to commit ind. offence', class = 'Indictable', id = 'Sect 114 Crimes Act', months = 10, fine = 10000, color = 'orange'},
        [6] = {title = 'Theft', class = 'Indictable', id = 'Sect 117 Crimes Act', months = 10, fine = 10000, color = 'orange'},
        [7] = {title = 'Stealing aircraft', class = 'Indictable', id = 'Sect 154B Crimes Act', months = 30, fine = 30000, color = 'orange'},
        [8] = {title = 'Stealing firearms', class = 'Indictable', id = 'Sect 154D Crimes Act', months = 30, fine = 30000, color = 'orange'},
        [9] = {title = 'Stealing motor vehicle, vessel or trailer (NPC)', class = 'Summary', id = 'Sect 154F Crimes Act', months = 5, fine = 1000, color = 'green'},
        [10] = {title = 'Stealing motor vehicle, vessel or trailer (Player)', class = 'Indictable', id = 'Sect 154F Crimes Act', months = 15, fine = 8000, color = 'orange'},
        [11] = {title = 'Fraud', class = 'Indictable', id = 'Sect 192E Crimes Act', months = 15, fine = 8000, color = 'orange'},
        [12] = {title = 'Possess ID w/ intent to commit ind. offence', class = 'Indictable', id = 'Sect 192K Crimes Act', months = 15, fine = 5000, color = 'orange'},
        [13] = {title = 'Possess equip. to make false ID', class = 'Indictable', id = 'Sect 192L Crimes Act', months = 15, fine = 5000, color = 'orange'},
        [14] = {title = 'Money Laundering', class = 'Indictable', id = 'Sect 193B Crimes Act', months = 25, fine = 25000, color = 'orange'},
        [15] = {title = 'Deal w/ suspected proceeds of crime (<100k)', class = 'Summary', id = 'Sect 193C (2) Crimes Act', months = 10, fine = 15000, color = 'green'},
        [16] = {title = 'Deal w/ suspected proceeds of crime (>100k)', class = 'Indictable', id = 'Sect 193C (1) Crimes Act', months = 25, fine = 20000, color = 'orange'},
        [17] = {title = 'Corrupting Betting Outcome of Event', class = 'Summary', id = 'Sect 193H Crimes Act', months = 15, fine = 15000, color = 'green'},
        [18] = {title = 'Using false document', class = 'Indictable', id = 'Sect 254 Crimes Act', months = 10, fine = 10000, color = 'orange'},
        [19] = {title = 'Possession of false document', class = 'Indictable', id = 'Sect 255 Crimes Act', months = 10, fine = 10000, color = 'orange'},
        [20] = {title = 'Computer Hacking', class = 'Indictable', id = 'Sect 308C Crimes Act', months = 15, fine = 10000, color = 'orange'},
        [21] = {title = 'Posession of data for computer offence', class = 'Indictable', id = 'Sect 308F Crimes Act', months = 15, fine = 10000, color = 'orange'},
        [22] = {title = 'Unauthorised access to restricted data', class = 'Summary', id = 'Sect 308H Crimes Act', months = 15, fine = 5000, color = 'green'},




    },

        --  Drugs
    [3] = {
        [1] = {title = 'Possess prohibited drug', class = 'Summary', id = 'S10 Drug Misuse & Trafficking Act', months = 25, fine = 7500, color = 'green'},
        [2] = {title = 'Possess equip. for prohib. drug use', class = 'Summary', id = 'Sect 11 Drug Misuse and Trafficking Act', months = 10, fine = 2000, color = 'green'},
        [3] = {title = 'Forging prescriptions', class = 'Summary', id = 'S15 Drug Misuse & Trafficking Act', months = 25, fine = 7500, color = 'green'},
        [4] = {title = 'Obtain prescription by false representation', class = 'Summary', id = 'S15 Drug Misuse & Trafficking Act', months = 25, fine = 7500, color = 'green'},
        [5] = {title = 'Cultivate prohibited plant', class = 'Indictable', id = 'S23 Drug Misuse & Trafficking Act', months = 30, fine = 15000, color = 'orange'},
        [6] = {title = 'Manufacture/produce prohibited drugs', class = 'Indictable', id = 'S24 Drug Misuse & Trafficking Act', months = 30, fine = 15000, color = 'orange'},
        [7] = {title = 'Possess precursors for production of prohibited drugs', class = 'Indictable', id = 'S24 Drug Misuse & Trafficking Act', months = 30, fine = 15000, color = 'orange'},
        [8] = {title = 'Poss. trafficable qty of prohib. drugs', class = 'Indictable', id = 'S25 Drug Misuse & Trafficking Act', months = 40, fine = 15000, color = 'orange'},
        [9] = {title = 'Supply prohibited drugs', class = 'Indictable', id = 'S25 Drug Misuse & Trafficking Act', months = 30, fine = 15000, color = 'orange'},
        [10] = {title = 'Supply prohib. drugs (Commercial)', class = 'Indictable', id = 'S25 Drug Misuse & Trafficking Act', months = 45, fine = 30000, color = 'red'},
        [11] = {title = 'Supply prohib. drugs (Large Commercial)', class = 'Indictable', id = 'S25 Drug Misuse & Trafficking Act', months = 70, fine = 50000, color = 'red'},
    },
        -- Property Damage / Environment
    [4] = {
        [1] = {title = 'Destroying or damaging property', class = 'Indictable', id = 'Sect 195 Crimes Act', months = 10, fine = 10000, color = 'orange'},
        [2] = {title = 'Arson', class = 'Indictable', id = 'Sect 195 Crimes Act', months = 20, fine = 10000, color = 'orange'},
        [3] = {title = 'Marking Premises or Property (Graffiti)', class = 'Summary', id = 'Sect 4 Graffiti Control Act', months = 0, fine = 5000, color = 'green'},
        [4] = {title = 'Poss. graffiti implement w/ intent to mark graffiti', class = 'Summary', id = 'Sect 5 Graffiti Control Act', months = 20, fine = 1000, color = 'green'},
        [5] = {title = 'Littering', class = 'Summary', id = 'S145 Protection of the Environment Act', months = 0, fine = 1000, color = 'green'},
        [6] = {title = 'Aggravated Littering', class = 'Summary', id = 'S145A Protection of the Environment Act', months = 0, fine = 2000, color = 'green'},
        [7] = {title = 'Unlicensed Hunting', class = 'Summary', id = 'S16 Game & Feral Animal Control Act', months = 0, fine = 5000, color = 'green'},
        [8] = {title = 'Contravene Hunting Licence Conditions', class = 'Summary', id = 'S23 Game & Feral Animal Control Act', months = 0, fine = 5000, color = 'green'},
        [9] = {title = 'Harm protected species', class = 'Summary', id = 'Sect 2.1 Biodiversity Conservation Act', months = 0, fine = 5000, color = 'green'},
        [10] = {title = 'Dealing in protected animals or plants', class = 'Summary', id = 'Sect 2.1 Biodiversity Conservation Act', months = 0, fine = 5000, color = 'green'},
        [11] = {title = 'Misconduct with regard to corpses', class = 'Indictable', id = 'Sect 81C Crimes Act', months = 20, fine = 10000, color = 'orange'},

    },
    -- Weapons
    [5] = {
        --[1] = {title = 'Discharging a Firearm with Intent', class = 'Indictable', id = 'Sect 33A Crimes Act', months = 40, fine = 7500, color = 'orange'},
        --[2] = {title = 'Use/possess weapon to resist arrest', class = 'Indictable', id = 'Sect 33B Crimes Act', months = 30, fine = 5000, color = 'orange'},
        [1] = {title = 'Possess explosives', class = 'Indictable', id = 'Sect 93FA (1) Crimes Act', months = 20, fine = 50000, color = 'orange'},
        [2] = {title = 'Supply or make explosives', class = 'Indictable', id = 'Sect 93FA(2) Crimes Act', months = 30, fine = 100000, color = 'orange'},
        [3] = {title = 'Possess dangerous article', class = 'Summary', id = 'Sect 93FB Crimes Act', months = 15, fine = 15000, color = 'green'},
        [4] = {title = 'Possession of unreg. firearm in public place', class = 'Indictable', id = 'Sect 93I Crimes Act', months = 20, fine = 15000, color = 'orange'},
        [5] = {title = 'Convey false info that person/property is in danger (Bomb Hoax etc)', class = 'Indictable', id = 'Sect 93Q Crimes Act', months = 20, fine = 20000, color = 'orange'},
        [6] = {title = 'Leave/send article w/ intent to cause alarm (Bomb Hoax etc)', class = 'Indictable', id = 'Sect 93R Crimes Act', months = 20, fine = 20000, color = 'orange'},
        [7] = {title = 'Custody of knife in public place', class = 'Summary', id = 'S11C Summary Offences Act', months = 0, fine = 5000, color = 'green'},
        [8] = {title = 'Possess Prohibited Weapon', class = 'Summary', id = 'Sect 7 Weapon Prohibition Act', months = 0, fine = 5000, color = 'green'},



    },
    -- Public Order & Custody
    [6] = {
        [1] = {title = 'Riot', class = 'Indictable', id = 'Sect 93B Crimes Act', months = 20, fine = 10000, color = 'orange'},
        [2] = {title = 'Affray', class = 'Indictable', id = 'Sect 93C Crimes Act', months = 10, fine = 10000, color = 'orange'},
        [3] = {title = 'Participation in criminal groups', class = 'Indictable', id = 'Sect 93T Crimes Act', months = 20, fine = 10000, color = 'orange'},
        [4] = {title = 'Conducting unlawful gambling operation', class = 'Summary', id = 'Sect 93V Crimes Act', months = 10, fine = 10000, color = 'green'},
        [5] = {title = 'Threatening/inciting violence on grounds of predjudice', class = 'Indictable', id = 'Sect 93Z Crimes Act', months = 30, fine = 30000, color = 'orange'},
        [6] = {title = 'Rescuing inmate from lawful custody', class = 'Indictable', id = 'Sect 310B Crimes Act', months = 50, fine = 50000, color = 'orange'},
        [7] = {title = 'Aiding escape', class = 'Indictable', id = 'Sect 310C Crimes Act', months = 30, fine = 30000, color = 'orange'},
        [8] = {title = 'Escape lawful custody', class = 'Indictable', id = 'Sect 310D Crimes Act', months = 40, fine = 40000, color = 'orange'},
        [9] = {title = 'Harbouring escapee', class = 'Indictable', id = 'Sect 310G Crimes Act', months = 20, fine = 20000, color = 'orange'},
        [10] = {title = 'Offensive Conduct or Language', class = 'Summary', id = 'Sect 4 Summary Offences Act', months = 0, fine = 1500, color = 'green'},
       -- [11] = {title = 'Obscene Exposure', class = 'Summary', id = 'Sect 5 Summary Offences Act', months = 0, fine = 1500, color = 'green'},
        [11] = {title = 'Obstructing Traffic', class = 'Summary', id = 'Sect 6 Summary Offences Act', months = 0, fine = 1500, color = 'green'},
        [12] = {title = 'Unauthorised Entry of Vehicle or Boat', class = 'Summary', id = 'Sect 5 Summary Offences Act', months = 0, fine = 1500, color = 'green'},
        [13] = {title = 'Obscene Exposure', class = 'Summary', id = 'Sect 5 Summary Offences Act', months = 0, fine = 1500, color = 'green'},
        [14] = {title = 'Trespassing, class', class = 'Summary', id = 'Sect 4 Inclosed Land Act', months = 10, fine = 3500, color = 'green'},
        [15] = {title = 'Fail to comply with move on direction', class = 'Summary', id = 'Sect 199 LEPRA', months = 15, fine = 5000, color = 'green'},
        [16] = {title = 'Fail to leave licensed premises', class = 'Summary', id = 'Sect 77 Liquor Act', months = 0, fine = 2000, color = 'green'}


    },
    -- Obstruct Justice / Corruption
    [7] = {
        [1] = {title = 'Knowingly make false accusation', class = 'Indictable', id = 'Sect 314 Crimes Act', months = 10, fine = 10000, color = 'orange'},
        --[2] = {title = 'Hinder Investigation of Serious Indictable Offence', class = 'Indictable', id = 'Sect 315 Crimes Act', months = 25, fine = 10000, color = 'orange'},
        [2] = {title = 'Threatening or intimidating victims or witnesses', class = 'Indictable', id = 'Sect 315A Crimes Act', months = 15, fine = 15000, color = 'orange'},
        [3] = {title = 'Tampering with evidence', class = 'Indictable', id = 'Sect 317 Crimes Act', months = 15, fine = 15000, color = 'orange'},
        [4] = {title = 'Pervert the course of justice', class = 'Indictable', id = 'Sect 319 Crimes Act', months = 15, fine = 15000, color = 'orange'},
        [5] = {title = 'Perjury', class = 'Summary', id = 'Sect 327 Crimes Act', months = 5, fine = 15000, color = 'green'},
        [6] = {title = 'Fail to disclose identity', class = 'Summary', id = 'Sect 12 LEPRA', months = 0, fine = 5000, color = 'green'},
        [7] = {title = 'Provide false or misleading info about identity', class = 'Summary', id = 'Sect 12 LEPRA', months = 0, fine = 5000, color = 'green'},
        [8] = {title = 'Failure to remove face covering', class = 'Summary', id = 'Sect 19B LEPRA', months = 0, fine = 2000, color = 'green'},
        [9] = {title = 'Resist/Hinder Police', class = 'Summary', id = 'Sect 39 LEPRA', months = 15, fine = 5000, color = 'green'},
        [10] = {title = 'Incite Person to Resist/Hinder Police', class = 'Summary', id = 'Sect 39 LEPRA', months = 15, fine = 5000, color = 'green'},
        [11] = {title = 'Use/posses weapon to resist arrest etc', class = 'Indictable', id = 'Sect 33B Crimes Act', months = 30, fine = 15000, color = 'orange'},
        [12] = {title = 'Bribery', class = 'Indictable', id = 'Common Law', months = 30, fine = 15000, color = 'orange'},
        [13] = {title = 'Fail to appear at court', class = 'Summary', id = 'Sect 79 Bail Act', months = 30, fine = 15000, color = 'green'},
        [14] = {title = 'Contempt of court', class = 'Summary', id = 'Sect 24 Local Court Act', months = 15, fine = 10000, color = 'green'},
        [15] = {title = 'Illegally record private conversation', class = 'Summary', id = 'S7 Surveillance Devices Act', months = 0, fine = 10000, color = 'green'},
        [16] = {title = 'Breach Apprehended Violence Order (AVO)', class = 'Indictable', id = 'S14 Crimes (DPV) Act', months = 20, fine = 10000, color = 'orange'},
        [17] = {title = 'Contravene Community Corrections Order', class = 'Indictable', id = 'S107C Crimes (Adm. of Sentences) Act', months = 30, fine = 10000, color = 'orange'},
        [18] = {title = 'Impersonation of Police Officers', class = 'Indictable', id = 'Sect 546D Crimes Act', months = 30, fine = 10000, color = 'orange'},
        [19] = {title = 'Engage in legal practice by unqualified entity', class = 'Summary', id = 'S10 Legal Profession Uniform Law', months = 10, fine = 10000, color = 'green'},
    },
    -- Firearms
    [8] = {
        [1] = {title = 'Discharging a Firearm with Intent to Cause Grevious Bodily Harm', class = 'Indictable', id = 'Sect 33A Crimes Act', months = 40, fine = 50000, color = 'orange'},
        [2] = {title = 'Possess Unregistered Firearm', class = 'Indictable', id = 'Sect 36(1) Firearms Act', months = 30, fine = 17500, color = 'orange'},
        [3] = {title = 'Fail to ensure safe keeping of a firearm', class = 'Summary', id = 'Sect 39 Firearms Act', months = 10, fine = 10000, color = 'green'},
        [4] = {title = 'Unauth. Possession/Use of Pistol', class = 'Indictable', id = 'Sect 7 Firearms Act', months = 10, fine = 15000, color = 'orange'},
        [5] = {title = 'Unauth. Possession/Use of Firearm (Non-pistol)', class = 'Summary', id = 'Sect 7A Firearms Act', months = 5, fine = 10000, color = 'green'},
        [6] = {title = 'Unauth. Possession/Use of Prohibited Firearm', class = 'Indictable', id = 'Sect 7 Firearms Act', months = 30, fine = 25000, color = 'orange'},
        [7] = {title = 'FPO subject Possess/Use/Aquire Firearm or Parts/Ammo', class = 'Indictable', id = 'Sect 74 Firearms Act', months = 20, fine = 15000, color = 'orange'},
        [8] = {title = 'Knowingly Supply Firearm or Parts/Ammo to FPO subject', class = 'Indictable', id = 'Sect 74 Firearms Act', months = 15, fine = 15000, color = 'orange'},
        [9] = {title = 'Possess loaded firearm in public place', class = 'Indictable', id = 'Sect 93G(1)(a) Crimes Act', months = 15, fine = 3000, color = 'orange'},
        [10] = {title = 'Discharge firearm in or near a public place', class = 'Indictable', id = 'Sect 93G(1)(b) Crimes Act', months = 15, fine = 3000, color = 'orange'},
        [11] = {title = 'Carry firearm in manner likely to injure', class = 'Indictable', id = 'Sect 93G(1)(c) Crimes Act', months = 15, fine = 3000, color = 'orange'},
    },
    --Traffic General
    [9] = {
        [1] = {title = 'Engage in a Police Pursuit', class = 'Indictable', id = 'Sect 51B Crimes Act', months = 50, fine = 50000, color = 'orange'},
        [2] = {title = 'Dangerous Driving Occassioning Death', class = 'Indictable', id = 'Sect 52A (1) Crimes Act', months = 50, fine = 50000, color = 'red'},
        [3] = {title = 'Dangerous Driving Occassioning Grevious Bodily Harm', class = 'Indictable', id = 'Sect 52A (3) Crimes Act', months = 30, fine = 20000, color = 'red'},
        [4] = {title = 'Fail to stop and assist after causing harm/death', class = 'Indictable', id = 'Sect 52AB Crimes Act', months = 20, fine = 10000, color = 'orange'},
        [5] = {title = 'Cause injury by furious driving', class = 'Indictable', id = 'Sect 53 Crimes Act', months = 20, fine = 10000, color = 'orange'},
        [6] = {title = 'Negligent Driving', class = 'Summary', id = 'Sect 117 Road Transport Act', months = 15, fine = 3000, color = 'green'},
        [7] = {title = 'Reckless Driving', class = 'Summary', id = 'Sect 117 Road Transport Act', months = 15, fine = 5000, color = 'green'},
        [8] = {title = 'Predatory Driving', class = 'Summary', id = 'Sect 51A Crimes Act', months = 25, fine = 15000, color = 'orange'},
        [9] = {title = 'Speed in Manner Dangerous', class = 'Summary', id = 'Sect 117 Road Transport Act', months = 15, fine = 3000, color = 'green'},
        [10] = {title = 'Failure of driver to disclose identity', class = 'Summary', id = 'Sect 12 LEPRA', months = 15, fine = 2000, color = 'green'},
        [11] = {title = 'Failure of owner to disclose identity', class = 'Summary', id = 'Sect 13 LEPRA', months = 15, fine = 2000, color = 'green'},
        [12] = {title = 'False information about identity of driver or passengers', class = 'Summary', id = 'Sect 18 LEPRA', months = 15, fine = 2000, color = 'green'},
        [13] = {title = 'Fail/refuse to stop vehicle when directed', class = 'Summary', id = 'Sect 39 LEPRA', months = 15, fine = 5000, color = 'green'},
        [14] = {title = 'Fail/refuse to comply with lawful direction (Traffic)', class = 'Summary', id = 'Sect 39 LEPRA', months = 15, fine = 5000, color = 'green'},
        [15] = {title = 'Not give particulars to other driver (Crashes)', class = 'Summary', id = 'Road Rules Rule 287', months = 15, fine = 5000, color = 'green'},
        [16] = {title = 'Not give particulars to injured person (Crashes)', class = 'Summary', id = 'Road Rules Rule 287', months = 15, fine = 5000, color = 'green'},
        [17] = {title = 'Not give particulars to owner of damaged property (Crashes)', class = 'Summary', id = 'Road Rules Rule 287', months = 15, fine = 5000, color = 'green'},
    },
    --Traffic - Defects & Licensing
    [10] = {
        [1] = {title = 'Driving without appropriate licence', class = 'Summary', id = 'Sect 53 Road Transport Act', months = 15, fine = 5000, color = 'green'},
        [2] = {title = 'Driving whilst suspended/disqualified', class = 'Summary', id = 'Sect 54 Road Transport Act', months = 15, fine = 5000, color = 'green'},
        [3] = {title = 'Make drivers licence application whilst suspended/disqualified', class = 'Summary', id = 'Sect 54 Road Transport Act', months = 15, fine = 5000, color = 'green'},
        [4] = {title = 'Driving an unregistered vehicle', class = 'Summary', id = 'Sect 68 Road Transport Act', months = 0, fine = 2000, color = 'green'},
        [5] = {title = 'Use vehicle not complying with roadworthy standards', class = 'Summary', id = 'RT (VR) Reg 2007', months = 0, fine = 1000, color = 'green'},
        [6] = {title = 'Start/Drive vehicle causing unnecessary noise/smoke', class = 'Summary', id = 'Road Rules 2014 Rule 291', months = 0, fine = 2000, color = 'green'},
        [7] = {title = 'Use vehicle in breach of minor defect notice', class = 'Summary', id = 'RT (VR) Reg 2017 Cl 128(2)', months = 0, fine = 2000, color = 'green'},
        [8] = {title = 'Use vehicle in breach of major defect notice', class = 'Summary', id = 'RT (VR) Reg 2017 Cl 128(2)', months = 0, fine = 3500, color = 'green'},
        [9] = {title = 'Use heavy vehicle in breach of minor defect notice', class = 'Summary', id = 'HVNL Sect 529', months = 0, fine = 5000, color = 'green'},
        [10] = {title = 'Use heavy vehicle in breach of major defect notice', class = 'Summary', id = 'HVNL Sect 529', months = 0, fine = 5000, color = 'green'},
    },
    --Traffic - Signs & Lights
    [11] = {
        [1] = {title = 'Proceed through red traffic light', class = 'Summary', id = 'Road Rules 2014 Rule 59(1)', months = 0, fine = 2500, color = 'green'},
        [2] = {title = 'Not stop before traffic lights at yellow light', class = 'Summary', id = 'Road Rules Rule 57 (1)(b)', months = 0, fine = 2500, color = 'green'},
        [3] = {title = 'Not stop at/before stop line/stop sign', class = 'Summary', id = 'Road Rules Rule 68 (1)', months = 0, fine = 2000, color = 'green'},
        [4] = {title = 'Not give way to vehicle (give way sign/line)', class = 'Summary', id = 'Road Rules Rule 69 (1)', months = 0, fine = 2000, color = 'green'},
        [5] = {title = 'Not give way to pedestrian on pedestrian crossing', class = 'Summary', id = 'Road Rules Rule 81 (2)', months = 0, fine = 2500, color = 'green'},
        [6] = {title = 'Drive contrary to direction of traffic lane arrow', class = 'Summary', id = 'Road Rules Rule 92 (1)', months = 0, fine = 1000, color = 'green'},
        [7] = {title = 'Pass / Overtake Vehicle contrary to no overtaking or passing sign', class = 'Summary', id = 'Road Rules Rule 93 (1)', months = 0, fine = 1000, color = 'green'},
        [8] = {title = 'Drive in emergency stopping lane', class = 'Summary', id = 'Road Rules Rule 95 (1)', months = 0, fine = 1000, color = 'green'},
        [9] = {title = 'Disobey no entry sign', class = 'Summary', id = 'Road Rules Rule 100', months = 0, fine = 1000, color = 'green'},
        [10] = {title = 'Disobey one-way sign', class = 'Summary', id = 'Road Rules Rule 98(1)', months = 0, fine = 1000, color = 'green'},
        [11] = {title = 'Unreasonably obstruct driver/pedestrian', class = 'Summary', id = 'Road Rules Rule 125(1)', months = 0, fine = 1000, color = 'green'},
        [12] = {title = 'Drive behind other vehicle too closely to stop safely', class = 'Summary', id = 'Road Rules Rule 126', months = 0, fine = 2500, color = 'green'},
        [13] = {title = 'Not keep right of dividing line', class = 'Summary', id = 'Road Rules Rule 132(2)', months = 0, fine = 2000, color = 'green'},
        [14] = {title = 'Drive on dividing strip', class = 'Summary', id = 'Road Rules Rule 137(1)', months = 0, fine = 1000, color = 'green'},
        [15] = {title = 'Illegal U-Turn', class = 'Summary', id = 'Road Rules Rule 37-42', months = 0, fine = 800, color = 'green'},

    },
    -- Traffic - Vehicle Operation
    [12] = {
        [1] = {title = 'Overtake vehicle when unsafe', class = 'Summary', id = 'Road Rules Rule 140', months = 0, fine = 2000, color = 'green'},
        [2] = {title = 'Cut in front of vehicle after overtaking', class = 'Summary', id = 'Road Rules Rule 144(b)', months = 0, fine = 2000, color = 'green'},
        [3] = {title = 'Ride motorcycle more than 2 abreast on road or in marked lane', class = 'Summary', id = 'Road Rules Rule 151', months = 0, fine = 1000, color = 'green'},
        [4] = {title = 'Leave engine on when vehicle unattended', class = 'Summary', id = 'Road Rules Rule 213(3)', months = 0, fine = 800, color = 'green'},
        [5] = {title = 'Not remove ignitiion key (vehicle unattended)', class = 'Summary', id = 'Road Rules Rule 213(4)', months = 0, fine = 800, color = 'green'},
        [6] = {title = 'Not secure windows/lock doors (vehicle unattended)', class = 'Summary', id = 'Road Rules Rule 213(4)', months = 0, fine = 800, color = 'green'},
        [7] = {title = 'Not secure windows/lock doors (vehicle unattended)', class = 'Summary', id = 'Road Rules Rule 213(5)', months = 0, fine = 800, color = 'green'},
        [8] = {title = 'Drive during period of darkness without prescribed lights', class = 'Summary', id = 'Road Rules Rule 215-1(1)', months = 0, fine = 800, color = 'green'},
        [9] = {title = 'Use high beam on oncoming vehicle', class = 'Summary', id = 'Road Rules Rule 218(1)', months = 0, fine = 800, color = 'green'},
        [10] = {title = 'Use horn unnecessarily', class = 'Summary', id = 'Road Rules Rule 224', months = 0, fine = 2000, color = 'green'},
        [11] = {title = 'Driver/rider/passenger use device to make sound like a siren', class = 'Summary', id = 'Road Rules Rule 224-1', months = 0, fine = 2000, color = 'green'},
        [12] = {title = 'Driver not wearing seatbelt', class = 'Summary', id = 'Road Rules Rule 264', months = 0, fine = 2000, color = 'green'},
        [13] = {title = 'Passenger not wear seatbelt properly', class = 'Summary', id = 'Road Rules Rule 267', months = 0, fine = 2000, color = 'green'},
        [14] = {title = 'Travel in/on vehicle in part not for passengers/goods', class = 'Summary', id = 'Road Rules Rule 268', months = 0, fine = 2000, color = 'green'},
        [15] = {title = 'Travel in/on boot of motor vehicle', class = 'Summary', id = 'Road Rules Rule 268-1', months = 0, fine = 2000, color = 'green'},
        [16] = {title = 'Drive motor vehicle with persons in or on boot', class = 'Summary', id = 'Road Rules Rule 268-2', months = 0, fine = 2000, color = 'green'},
        [17] = {title = 'Ride motorcycle with no helmet', class = 'Summary', id = 'Road Rules Rule 270(1)(a)', months = 0, fine = 2000, color = 'green'},
        [18] = {title = 'Ride motorcycle with one unhelmeted passenger', class = 'Summary', id = 'Road Rules Rule 270(1)(b)', months = 0, fine = 2000, color = 'green'},
        [19] = {title = 'Motorcycle passenger not wearing helmet', class = 'Summary', id = 'Road Rules Rule 270(2)', months = 0, fine = 2000, color = 'green'},
        [20] = {title = 'Drive on path', class = 'Summary', id = 'Road Rules Rule 287', months = 0, fine = 2000, color = 'green'},
        [21] = {title = 'Drive on nature strip', class = 'Summary', id = 'Road Rules Rule 289', months = 0, fine = 2000, color = 'green'},
        [22] = {title = 'Drive on traffic island', class = 'Summary', id = 'Road Rules Rule 289', months = 0, fine = 2000, color = 'green'},
        [23] = {title = 'Drive/tow vehicle with unsecured load', class = 'Summary', id = 'Road Rules Rule 292(a)', months = 0, fine = 2500, color = 'green'},
        [24] = {title = 'Not reverse safely', class = 'Summary', id = 'Road Rules Rule 296(1)', months = 0, fine = 192, color = 'green'},
        [25] = {title = 'Drive without proper control of vehicle', class = 'Summary', id = 'Road Rules Rule 297(1)', months = 0, fine = 2500, color = 'green'},
        [26] = {title = 'Drive motor vehicle with person or animal in lap', class = 'Summary', id = 'Road Rules Rule 297(1A)', months = 0, fine = 2500, color = 'green'},
        [27] = {title = 'Drive using mobile phone when not permitted', class = 'Summary', id = 'Road Rules Rule 300', months = 0, fine = 2000, color = 'green'},
        [28] = {title = 'Driver consume alcohol while driving', class = 'Summary', id = 'Road Rules Rule 298', months = 0, fine = 2000, color = 'green'},
        [29] = {title = 'Driver motor vehicle not carry licence', class = 'Summary', id = 'Road Rules Rule 300-5', months = 0, fine = 2000, color = 'green'},
        [30] = {title = 'Not obey direction of police/authorised person', class = 'Summary', id = 'Road Rules Rule 304(1)', months = 0, fine = 2000, color = 'green'},
        [31] = {title = 'Burnout', class = 'Summary', id = 'Sect 116 Road Transport Act', months = 0, fine = 3000, color = 'green'},
        [32] = {title = 'Use vehicle without correctly fixed/displayed number plate', class = 'Summary', id = 'Road Rules (VR) Cl 60', months = 0, fine = 2500, color = 'green'},
        [33] = {title = 'Use vehicle displaying misleading plate', class = 'Summary', id = 'Road Rules (VR) Cl 129 (3)(b)', months = 0, fine = 2500, color = 'green'},
        [34] = {title = 'Drive/use vehicle with sound system emitting offensive noise', class = 'Summary', id = 'Prot Env (Noise Control) Reg 2017 Cl 33(1)', months = 0, fine = 300, color = 'green'},
        [35] = {title = 'Organise, promote, or take part in street race', class = 'Summary', id = 'Sect 115 Road Transport Act', months = 15, fine = 10000, color = 'green'},
    },

    --Speeding
    [13] = {

        [1] = {title = 'Exceed Speed over 10kmph', class = 'Summary', id = 'Road Rules Rule 20', months = 0, fine = 2000, color = 'green'},
        [2] = {title = 'Exceed Speed over 20kmph', class = 'Summary', id = 'Road Rules Rule 20', months = 0, fine = 5000, color = 'green'},
        [3] = {title = 'Exceed Speed over 30kmph', class = 'Summary', id = 'Road Rules Rule 20', months = 0, fine = 15000, color = 'green'},
        [4] = {title = 'Exceed Speed over 45kmph', class = 'Summary', id = 'Road Rules Rule 20', months = 0, fine = 20000, color = 'green'},
        [5] = {title = 'Exceed Speed over 10kmph (Heavy Vehicle)', class = 'Summary', id = 'Road Rules Rule 20', months = 0, fine = 4000, color = 'green'},
        [6] = {title = 'Exceed Speed over 20kmph (Heavy Vehicle)', class = 'Summary', id = 'Road Rules Rule 20', months = 0, fine = 8000, color = 'green'},
        [7] = {title = 'Exceed Speed over 30kmph (Heavy Vehicle)', class = 'Summary', id = 'Road Rules Rule 20', months = 0, fine = 20000, color = 'green'},
        [8] = {title = 'Exceed Speed over 45kmph (Heavy Vehicle)', class = 'Summary', id = 'Road Rules Rule 20', months = 0, fine = 30000, color = 'green'},

    },
    --Drink / Drug Driving
    [14] = {

        [1] = {title = 'Low-range drink driving (BAC 0.05 - 0.079)', class = 'Summary', id = 'Sect 110 Road Transport Act', months = 0, fine = 1000, color = 'green'},
        [2] = {title = 'Mid-range drink driving (BAC 0.08 - 0.149)', class = 'Summary', id = 'Sect 110 Road Transport Act', months = 12, fine = 3000, color = 'green'},
        [3] = {title = 'High-range drink driving (BAC 0.15 or higher)', class = 'Summary', id = 'Sect 110 Road Transport Act', months = 24, fine = 5000, color = 'green'},
        [4] = {title = 'Drive with presence of illicit drugs in system', class = 'Summary', id = 'Sect 111 Road Transport Act', months = 0, fine = 5000, color = 'green'},
        [5] = {title = 'Driving under the influence', class = 'Summary', id = 'Sect 112 Road Transport Act', months = 18, fine = 5000, color = 'green'},


    },
}

Config.PoliceJobs = {
    ['police'] = true,
    ['lspd'] = true,
    ['bcso'] = true,
    ['sast'] = true,
    ['sasp'] = true,
    ['doc'] = true,
    ['sapr'] = true,
    ['pa'] = true -- yucky
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = true
}

Config.DojJobs = {
    ['lawyer'] = true,
}

-- Leave my hacky code alone ya goblins
Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end
-- Leave my hacky code alone ya goblins

Config.LogPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
}

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end

-- this is a hack, because the qb-menu in qb-policejob populates an impound location and passed it through to the event.
-- if this impound locations are changed in qb-policejob, they must also be changed here.
Config.ImpoundLocations = {
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}
